### ISSUE TITLE
Numba caching issue in NOMAD

### ISSUE THREAD

**Issue by mkuehbach** [FAIRmat-NFDI/pynxtools-em#73]
[Using SprintNomadBaseSectionEmApmFixes branch from ](https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/tree/SprintNomadBaseSectionEmApmFixes), py3.11, and pynxtools[convert]==0.7.1 oasis deployments show an issue

"root":{
"normalizer":string"MetainfoNormalizer"
"mainfile":string"em.nxs"
"event":string"could not convert to nxs"
"proc":string"Entry"
"process":string"process_entry"
"process_worker_id":string"1_G2coQzQ9yN6UJ5HsE3nQ"
"parser":string"parsers/archive"
"step":string"MetainfoNormalizer"
"logger":string"nomad.processing"
"exception":string"Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/pynxtools/dataconverter/convert.py", line 73, in get_reader spec.loader.exec_module(module) # type: ignore[attr-defined] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap_external>", line 936, in exec_module File "<frozen importlib._bootstrap_external>", line 1073, in get_code File "<frozen importlib._bootstrap_external>", line 1130, in get_data FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.11/site-packages/pynxtools/dataconverter/readers/em/reader.py' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/pynxtools/nomad/dataconverter.py", line 226, in normalize pynxtools_converter.convert(**converter_params) File "/usr/local/lib/python3.11/site-packages/pynxtools/dataconverter/convert.py", line 230, in convert data = transfer_data_into_template( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pynxtools/dataconverter/convert.py", line 152, in transfer_data_into_template data_reader = get_reader(reader) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pynxtools/dataconverter/convert.py", line 80, in get_reader return importlib_module[reader_name].load() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/importlib_metadata/__init__.py", line 184, in load module = import_module(match.group('module')) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap>", line 1204, in _gcd_import File "<frozen importlib._bootstrap>", line 1176, in _find_and_load File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 690, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 940, in exec_module File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "/usr/local/lib/python3.11/site-packages/pynxtools_em/reader.py", line 29, in <module> from pynxtools_em.parsers.hfive_apex import HdfFiveEdaxApexParser File "/usr/local/lib/python3.11/site-packages/pynxtools_em/parsers/hfive_apex.py", line 26, in <module> from orix.quaternion import Orientation File "/usr/local/lib/python3.11/site-packages/orix/quaternion/__init__.py", line 25, in <module> from orix.quaternion.quaternion import Quaternion # isort: skip ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/orix/quaternion/quaternion.py", line 31, in <module> from orix.quaternion import _conversions File "/usr/local/lib/python3.11/site-packages/orix/quaternion/_conversions.py", line 44, in <module> @nb.jit("int64(float64[:])", cache=True, nogil=True, nopython=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/numba/core/decorators.py", line 225, in wrapper disp.enable_caching() File "/usr/local/lib/python3.11/site-packages/numba/core/dispatcher.py", line 808, in enable_caching self._cache = FunctionCache(self.py_func) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/numba/**core/caching.py", line 601, in __init__ self._impl = self._impl_class(py_func) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/numba/core/caching.py", line 337, in __init__ raise RuntimeError("cannot cache function %r: no locator available " RuntimeError: cannot cache function 'get_pyramid_single': no locator available for file '/usr/local/lib/python3.11/site-packages/orix/quaternion/_conversions.py**'"
"timestamp":string"2024-09-23 08:04.40"
"level":string"ERROR"

Hypothesis: https://github.com/numba/numba/issues/9668 numpy caching unable/not having write permission into container, hence numba cannot be imported, hence kikuchipy can not be imported, in summary, NeXus parsing gets interrupted.

Local installations made from this NOMAD branch and pynxtools work fine out of the box (cuz here numpy will be sitting typically in editable local venv with access rights)
https://github.com/SeldonIO/alibi-detect/issues/435

https://github.com/numba/numba/issues/4032 bjarthur

**Comment by mkuehbach** [comment]
Suggestion from Ahmed Ilyas, add env directly in nomad-lab nomad-FAIR Dockerfile and deploy from there for testing

**Comment by mkuehbach** [comment]
@lukaspie reported that above-mentioned suggestion implemented in NOMAD solved the issue
